name: Run Python script and upload to S3

on:
  push:
    branches:
      - main  # или любая другая ветка, которую вы хотите отслеживать

jobs:
  run-script-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # укажите нужную версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Python script in DEBUG mode
        run: |
          python create_file.py path/to/directory DEBUG

      - name: Upload DEBUG file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 cp path/to/directory/outDebug/outputDebug.txt s3://testbs23123/outDebug/outputDebug.txt

      - name: Run Python script in RELEASE mode
        run: |
          python create_file.py path/to/directory RELEASE

      - name: Upload RELEASE file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 cp path/to/directory/outRelease/outputRelease.txt s3://testbs23123/outRelease/outputRelease.txt
