name: Run Python script and upload to AWS

on:
  push:
    branches:
      - main  # или любая другая ветка, которую вы хотите отслеживать

jobs:
  run-script-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # укажите нужную версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3  # Устанавливаем библиотеку для работы с AWS

      - name: Run Python script
        run: |
          python create_file.py /path/to/directory

      - name: Upload to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 cp /path/to/directory/output.txt s3://your-bucket-name/output.txt
