name: Build and upload to S3

on:
  push:
    branches:
      - main
      
jobs:
  run-and-upload:
    name: Build and upload to S3
    runs-on: self-hosted

    strategy:
      matrix:
        mode: [DEBUG, RELEASE]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build ${{ github.event.repository.name }} ${{ matrix.mode }}
        run: |
          python create_file.py REPO_NAME
          
      - name: Upload to S3
        run: |
          aws s3 cp REPO_NAME s3://testbs23123/REPO_NAME
          
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          REPO_NAME: ${{ github.event.repository.name }}/${{ matrix.mode }}
