name: Run Python script and upload to S3

on:
  push:
    branches:
      - main
      
jobs:
  run-and-upload:
    name: Run Python script and upload to S3
    runs-on: self-hosted

    strategy:
      matrix:
        mode: [DEBUG, RELEASE]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Python script upload to S3
        run: |
          python create_file.py path/to/directory ${{ matrix.mode }}
          
      - name: Upload to S3
        run: |
          aws s3 cp path/to/directory/out${{ matrix.mode }}/output${{ matrix.mode }}.txt s3://testbs23123/out${{ matrix.mode }}/output${{ matrix.mode }}.txt
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
