name: Build and upload to S3

on:
  push:
    branches:
      - main
      
jobs:
  run-and-upload:
    name: Build and upload to S3
    runs-on: self-hosted

    strategy:
      matrix:
        mode: [DEBUG, RELEASE]
        
    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      MODE: ${{ matrix.mode }}
      BUILD_REPO_NAME: $PROJECT_NAME/$MODE
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ${{ env.PROJECT_NAME }} ${{ env.MODE }}
        run: |
          python create_file.py ${{ env.BUILD_REPO_NAME }} ${{ env.MODE }}
          
      - name: Upload to S3
        run: |
          aws s3 cp ${{ env.BUILD_REPO_NAME }} s3://testbs23123/${{ env.BUILD_REPO_NAME }} --recursive
          
